version: "3.8"
services:
  
  embedder:
    image: soumitsr/parrotbox:2024060502
    environment:
      - PORT=9000
    ports:
      - "9000"

  cdn:
    image: soumitsr/coffeemaker:2424060501
    expose:
      - 8080
    ports:
      - "80:8080"
      - "8080:8080"
    depends_on:
      - embedder
    environment:
      - INSTANCE_MODE=CDN   
      - EMBEDDER_BASE_URL=http://embedder:9000/embedding
      - PORT=8080    
    env_file:
      - docker.env
    
  indexer:
    image: soumitsr/coffeemaker:2424060501
    environment:
      - INSTANCE_MODE=INDEXER
      - COLLECTION_SCHEDULE=0 0 10,22 * * * # runs every day at 10PM and 10PM
      - RECTIFY_SCHEDULE=0 0 5 * * * # run every day at 5AM
      - CLEANUP_SCHEDULE=0 0 4 * * 0 # runs once a week on sunday 4AM
      - EMBEDDER_BASE_URL=http://embedder:9000/embedding
    env_file:
      - docker.env
    depends_on:
      - embedder

  
