name: Docker Build and Publish

on:
  push:
    branches:
      - main  # Change this to match your branch name
  pull_request: 
    branches:
      - main  # Change this to match your branch name

jobs:
  publish:
    name: Publish Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/coffeemaker:indexer -f Indexerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/coffeemaker:indexer
